<a href="https://colab.research.google.com/github/syedmahmoodiagents/gct/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame({
    "A": [10,20,30,40,50],
    "B": ['a', 'b', 'c', 'd', 'e']

})

In [5]:
df

    A  B
0  10  a
1  20  b
2  30  c
3  40  d
4  50  e

In [6]:
pd.DataFrame({
    "A": [10,20,30,40,50],
    "B": ['a', 'b', 'c', 'd', 'e'],
    "C": np.random.randint(0,9,5)
})

    A  B  C
0  10  a  3
1  20  b  2
2  30  c  2
3  40  d  2
4  50  e  7

In [8]:
pd.DataFrame(
    np.random.randint(0,9,(10, 4)), columns=["A", "B", "C", "D"]
)

   A  B  C  D
0  0  4  7  6
1  3  0  8  0
2  2  1  8  2
3  2  7  4  3
4  7  3  2  3
5  5  3  7  4
6  3  8  5  2
7  5  5  7  3
8  8  2  7  6
9  2  1  5  3

In [12]:
np.random.rand(10,3).round(2)

array([[0.32, 0.66, 0.99],
       [0.72, 0.54, 0.62],
       [0.05, 0.74, 0.64],
       [0.28, 0.5 , 0.05],
       [0.01, 0.84, 0.42],
       [0.32, 0.89, 0.48],
       [0.48, 0.01, 0.6 ],
       [0.04, 0.14, 0.75],
       [0.39, 0.66, 0.86],
       [0.78, 0.08, 0.09]])

In [15]:
# create the dataframe
dfx = pd.DataFrame(np.random.rand(100,3).round(2), columns=["AA", "BB", "CC"])

In [16]:
dfx

      AA    BB    CC
0   0.13  0.66  0.11
1   0.80  0.16  0.33
2   0.33  0.94  0.59
3   0.31  0.44  0.01
4   0.11  0.19  0.24
..   ...   ...   ...
95  0.08  0.74  0.98
96  0.61  0.09  0.69
97  0.51  0.41  0.69
98  0.06  0.32  0.62
99  0.43  0.16  0.08

[100 rows x 3 columns]

In [18]:
dfx.to_excel("abcd.xlsx") # store this file

In [22]:
df = pd.read_excel("newexl.xlsx", index_col="Unnamed: 0")

In [23]:
df

      AA    BB    CC
0   0.13  0.66  0.11
1   0.80  0.16  0.33
2   0.33  0.94  0.59
3   0.31  0.44  0.01
4   0.11  0.19  0.24
..   ...   ...   ...
95  0.08  0.74  0.98
96  0.61  0.09  0.69
97  0.51  0.41  0.69
98  0.06  0.32  0.62
99  0.43  0.16  0.08

[100 rows x 3 columns]

In [26]:
df['DD'] = np.random.randint(0,9,100)

In [27]:
df

      AA    BB    CC  DD
0   0.13  0.66  0.11   6
1   0.80  0.16  0.33   4
2   0.33  0.94  0.59   6
3   0.31  0.44  0.01   6
4   0.11  0.19  0.24   4
..   ...   ...   ...  ..
95  0.08  0.74  0.98   2
96  0.61  0.09  0.69   3
97  0.51  0.41  0.69   3
98  0.06  0.32  0.62   0
99  0.43  0.16  0.08   1

[100 rows x 4 columns]

In [28]:
df['MM'] = np.random.choice(["cat", "dog"], 100)

In [29]:
df

      AA    BB    CC  DD   MM
0   0.13  0.66  0.11   6  cat
1   0.80  0.16  0.33   4  dog
2   0.33  0.94  0.59   6  cat
3   0.31  0.44  0.01   6  dog
4   0.11  0.19  0.24   4  cat
..   ...   ...   ...  ..  ...
95  0.08  0.74  0.98   2  cat
96  0.61  0.09  0.69   3  cat
97  0.51  0.41  0.69   3  dog
98  0.06  0.32  0.62   0  dog
99  0.43  0.16  0.08   1  cat

[100 rows x 5 columns]

In [33]:
df.describe(include='all')

                AA          BB          CC          DD   MM
count   100.000000  100.000000  100.000000  100.000000  100
unique         NaN         NaN         NaN         NaN    2
top            NaN         NaN         NaN         NaN  dog
freq           NaN         NaN         NaN         NaN   51
mean      0.472700    0.531700    0.534800    4.060000  NaN
std       0.271099    0.298034    0.294088    2.489655  NaN
min       0.010000    0.000000    0.000000    0.000000  NaN
25%       0.267500    0.317500    0.280000    2.000000  NaN
50%       0.475000    0.525000    0.585000    4.000000  NaN
75%       0.682500    0.805000    0.802500    6.000000  NaN
max       1.000000    1.000000    1.000000    8.000000  NaN

In [34]:
df.drop('MM', axis=1)

      AA    BB    CC  DD
0   0.13  0.66  0.11   6
1   0.80  0.16  0.33   4
2   0.33  0.94  0.59   6
3   0.31  0.44  0.01   6
4   0.11  0.19  0.24   4
..   ...   ...   ...  ..
95  0.08  0.74  0.98   2
96  0.61  0.09  0.69   3
97  0.51  0.41  0.69   3
98  0.06  0.32  0.62   0
99  0.43  0.16  0.08   1

[100 rows x 4 columns]

In [35]:
df

      AA    BB    CC  DD   MM
0   0.13  0.66  0.11   6  cat
1   0.80  0.16  0.33   4  dog
2   0.33  0.94  0.59   6  cat
3   0.31  0.44  0.01   6  dog
4   0.11  0.19  0.24   4  cat
..   ...   ...   ...  ..  ...
95  0.08  0.74  0.98   2  cat
96  0.61  0.09  0.69   3  cat
97  0.51  0.41  0.69   3  dog
98  0.06  0.32  0.62   0  dog
99  0.43  0.16  0.08   1  cat

[100 rows x 5 columns]

In [36]:
dnx = df.drop('MM', axis=1)

In [37]:
dnx

      AA    BB    CC  DD
0   0.13  0.66  0.11   6
1   0.80  0.16  0.33   4
2   0.33  0.94  0.59   6
3   0.31  0.44  0.01   6
4   0.11  0.19  0.24   4
..   ...   ...   ...  ..
95  0.08  0.74  0.98   2
96  0.61  0.09  0.69   3
97  0.51  0.41  0.69   3
98  0.06  0.32  0.62   0
99  0.43  0.16  0.08   1

[100 rows x 4 columns]

In [ ]:
# df.drop('MM', axis=1, inplace=True)

In [38]:
dnx

      AA    BB    CC  DD
0   0.13  0.66  0.11   6
1   0.80  0.16  0.33   4
2   0.33  0.94  0.59   6
3   0.31  0.44  0.01   6
4   0.11  0.19  0.24   4
..   ...   ...   ...  ..
95  0.08  0.74  0.98   2
96  0.61  0.09  0.69   3
97  0.51  0.41  0.69   3
98  0.06  0.32  0.62   0
99  0.43  0.16  0.08   1

[100 rows x 4 columns]

# How to use conditions to create a new column

In [39]:
dnx['DD'].apply(lambda x: 'big' if x >= 5 else 'small')

0       big
1     small
2       big
3       big
4     small
      ...
95    small
96    small
97    small
98    small
99    small
Name: DD, Length: 100, dtype: object

In [40]:
dnx

      AA    BB    CC  DD
0   0.13  0.66  0.11   6
1   0.80  0.16  0.33   4
2   0.33  0.94  0.59   6
3   0.31  0.44  0.01   6
4   0.11  0.19  0.24   4
..   ...   ...   ...  ..
95  0.08  0.74  0.98   2
96  0.61  0.09  0.69   3
97  0.51  0.41  0.69   3
98  0.06  0.32  0.62   0
99  0.43  0.16  0.08   1

[100 rows x 4 columns]

In [41]:
dnx['MM'] = dnx['DD'].apply(lambda x: 'big' if x >= 5 else 'small')

In [42]:
dnx

      AA    BB    CC  DD     MM
0   0.13  0.66  0.11   6    big
1   0.80  0.16  0.33   4  small
2   0.33  0.94  0.59   6    big
3   0.31  0.44  0.01   6    big
4   0.11  0.19  0.24   4  small
..   ...   ...   ...  ..    ...
95  0.08  0.74  0.98   2  small
96  0.61  0.09  0.69   3  small
97  0.51  0.41  0.69   3  small
98  0.06  0.32  0.62   0  small
99  0.43  0.16  0.08   1  small

[100 rows x 5 columns]