In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import make_regression, load_iris

# Using load_based dataset

In [4]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [41]:
dt = load_iris()

In [42]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [43]:
df = pd.DataFrame(dt.data, columns=dt.feature_names)

In [44]:
df.rename(columns={'sepal length (cm)':'sepal_length', 'sepal width (cm)':'sepal_width', 'petal length (cm)':'petal_length', 'petal width (cm)':'petal_width'}, inplace=True)

In [18]:
df

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [49]:
df['target'] = dt.target

In [50]:
df

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [51]:
df[df['sepal_length']>5]

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
5             5.4          3.9           1.7          0.4       0
10            5.4          3.7           1.5          0.2       0
14            5.8          4.0           1.2          0.2       0
15            5.7          4.4           1.5          0.4       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[118 rows x 5 columns]

In [52]:
df.loc[df['sepal_length']>5, ['sepal_length', 'sepal_width']]

     sepal_length  sepal_width
0             5.1          3.5
5             5.4          3.9
10            5.4          3.7
14            5.8          4.0
15            5.7          4.4
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[118 rows x 2 columns]

In [59]:
df.loc[df['sepal_length']< 6, 'new_column'] = 'small sepals'

In [61]:
df.loc[df['sepal_length']>= 6, 'new_column'] = 'big sepals'

In [65]:
df['updated_column'] = df['sepal_length'].apply(lambda x: 'smaller sepals' if x < 6 else 'large sepals')

In [66]:
df

,sepal_length,sepal_width,petal_length,petal_width,target,new_column,updated_column
0,5.1,3.5,1.4,0.2,0,small sepals,smaller sepals
1,4.9,3.0,1.4,0.2,0,small sepals,smaller sepals
2,4.7,3.2,1.3,0.2,0,small sepals,smaller sepals
3,4.6,3.1,1.5,0.2,0,small sepals,smaller sepals
4,5.0,3.6,1.4,0.2,0,small sepals,smaller sepals
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,big sepals,large sepals
146,6.3,2.5,5.0,1.9,2,big sepals,large sepals
147,6.5,3.0,5.2,2.0,2,big sepals,large sepals
148,6.2,3.4,5.4,2.3,2,big sepals,large sepals
149,5.9,3.0,5.1,1.8,2,small sepals,smaller sepals

# Using Make_based dataset

In [19]:
x,y = make_regression(n_samples=20, n_features=4, bias=10.3, noise=1.8)

In [20]:
x.shape

(20, 4)

In [21]:
y.shape

(20,)

In [22]:
df = pd.DataFrame(x).round(2)

In [23]:
df

       0     1     2     3
0   0.73 -1.18 -0.46 -0.47
1   0.47  0.09  0.38  0.44
2  -0.81  1.89  1.05 -1.27
3   0.11 -1.26  0.63  0.82
4   0.46 -0.48  1.31 -0.53
5  -0.35 -0.06 -0.19  0.12
6  -1.40  1.04  1.39  0.92
7  -1.52  0.25 -0.41 -1.35
8  -1.49 -0.09  0.65  0.32
9   0.20  0.95 -0.08 -0.05
10 -0.88 -0.58  0.84 -0.14
11 -0.14 -0.15  0.87 -1.10
12 -1.36 -0.67 -1.57 -1.76
13 -0.18 -0.10 -0.01 -0.19
14 -2.03 -0.43  2.57  0.90
15 -1.29  0.58 -0.43  0.15
16  0.91 -1.03  0.04  0.22
17 -0.18  0.90  0.25  1.12
18 -1.25  1.87 -0.03  0.26
19  1.24 -0.36  0.43 -0.01

In [24]:
df.columns = ["col1", "col2", "col3", "col4"]

In [25]:
df.rename()

TypeError: must pass an index to rename

In [26]:
df

    col1  col2  col3  col4
0   0.73 -1.18 -0.46 -0.47
1   0.47  0.09  0.38  0.44
2  -0.81  1.89  1.05 -1.27
3   0.11 -1.26  0.63  0.82
4   0.46 -0.48  1.31 -0.53
5  -0.35 -0.06 -0.19  0.12
6  -1.40  1.04  1.39  0.92
7  -1.52  0.25 -0.41 -1.35
8  -1.49 -0.09  0.65  0.32
9   0.20  0.95 -0.08 -0.05
10 -0.88 -0.58  0.84 -0.14
11 -0.14 -0.15  0.87 -1.10
12 -1.36 -0.67 -1.57 -1.76
13 -0.18 -0.10 -0.01 -0.19
14 -2.03 -0.43  2.57  0.90
15 -1.29  0.58 -0.43  0.15
16  0.91 -1.03  0.04  0.22
17 -0.18  0.90  0.25  1.12
18 -1.25  1.87 -0.03  0.26
19  1.24 -0.36  0.43 -0.01

In [27]:
df.rename(columns={
    "col1":"delhi",
    "col2":"mumbai",
    "col3":"bengluru",
    "col4":"chennai"
}, inplace=True)

In [28]:
df

    delhi  mumbai  bengluru  chennai
0    0.73   -1.18     -0.46    -0.47
1    0.47    0.09      0.38     0.44
2   -0.81    1.89      1.05    -1.27
3    0.11   -1.26      0.63     0.82
4    0.46   -0.48      1.31    -0.53
5   -0.35   -0.06     -0.19     0.12
6   -1.40    1.04      1.39     0.92
7   -1.52    0.25     -0.41    -1.35
8   -1.49   -0.09      0.65     0.32
9    0.20    0.95     -0.08    -0.05
10  -0.88   -0.58      0.84    -0.14
11  -0.14   -0.15      0.87    -1.10
12  -1.36   -0.67     -1.57    -1.76
13  -0.18   -0.10     -0.01    -0.19
14  -2.03   -0.43      2.57     0.90
15  -1.29    0.58     -0.43     0.15
16   0.91   -1.03      0.04     0.22
17  -0.18    0.90      0.25     1.12
18  -1.25    1.87     -0.03     0.26
19   1.24   -0.36      0.43    -0.01

In [29]:
pd.date_range("2026-07-05", periods=20, freq="W")

DatetimeIndex(['2026-07-05', '2026-07-12', '2026-07-19', '2026-07-26',
               '2026-08-02', '2026-08-09', '2026-08-16', '2026-08-23',
               '2026-08-30', '2026-09-06', '2026-09-13', '2026-09-20',
               '2026-09-27', '2026-10-04', '2026-10-11', '2026-10-18',
               '2026-10-25', '2026-11-01', '2026-11-08', '2026-11-15'],
              dtype='datetime64[ns]', freq='W-SUN')

In [30]:
df.set_index(pd.date_range("2026-07-05", periods=20, freq="W"), inplace=True)

In [31]:
df

            delhi  mumbai  bengluru  chennai
2026-07-05   0.73   -1.18     -0.46    -0.47
2026-07-12   0.47    0.09      0.38     0.44
2026-07-19  -0.81    1.89      1.05    -1.27
2026-07-26   0.11   -1.26      0.63     0.82
2026-08-02   0.46   -0.48      1.31    -0.53
2026-08-09  -0.35   -0.06     -0.19     0.12
2026-08-16  -1.40    1.04      1.39     0.92
2026-08-23  -1.52    0.25     -0.41    -1.35
2026-08-30  -1.49   -0.09      0.65     0.32
2026-09-06   0.20    0.95     -0.08    -0.05
2026-09-13  -0.88   -0.58      0.84    -0.14
2026-09-20  -0.14   -0.15      0.87    -1.10
2026-09-27  -1.36   -0.67     -1.57    -1.76
2026-10-04  -0.18   -0.10     -0.01    -0.19
2026-10-11  -2.03   -0.43      2.57     0.90
2026-10-18  -1.29    0.58     -0.43     0.15
2026-10-25   0.91   -1.03      0.04     0.22
2026-11-01  -0.18    0.90      0.25     1.12
2026-11-08  -1.25    1.87     -0.03     0.26
2026-11-15   1.24   -0.36      0.43    -0.01

In [32]:
df.to_excel("regression.xlsx")

In [34]:
ndf = pd.read_excel("regression.xlsx", index_col="Unnamed: 0")

In [35]:
ndf

            delhi  mumbai  bengluru  chennai
2026-07-05   0.73   -1.18     -0.46    -0.47
2026-07-12   0.47    0.09      0.38     0.44
2026-07-19  -0.81    1.89      1.05    -1.27
2026-07-26   0.11   -1.26      0.63     0.82
2026-08-02   0.46   -0.48      1.31    -0.53
2026-08-09  -0.35   -0.06     -0.19     0.12
2026-08-16  -1.40    1.04      1.39     0.92
2026-08-23  -1.52    0.25     -0.41    -1.35
2026-08-30  -1.49   -0.09      0.65     0.32
2026-09-06   0.20    0.95     -0.08    -0.05
2026-09-13  -0.88   -0.58      0.84    -0.14
2026-09-20  -0.14   -0.15      0.87    -1.10
2026-09-27  -1.36   -0.67     -1.57    -1.76
2026-10-04  -0.18   -0.10     -0.01    -0.19
2026-10-11  -2.03   -0.43      2.57     0.90
2026-10-18  -1.29    0.58     -0.43     0.15
2026-10-25   0.91   -1.03      0.04     0.22
2026-11-01  -0.18    0.90      0.25     1.12
2026-11-08  -1.25    1.87     -0.03     0.26
2026-11-15   1.24   -0.36      0.43    -0.01

In [36]:
ndf.loc[:,'delhi']

2026-07-05    0.73
2026-07-12    0.47
2026-07-19   -0.81
2026-07-26    0.11
2026-08-02    0.46
2026-08-09   -0.35
2026-08-16   -1.40
2026-08-23   -1.52
2026-08-30   -1.49
2026-09-06    0.20
2026-09-13   -0.88
2026-09-20   -0.14
2026-09-27   -1.36
2026-10-04   -0.18
2026-10-11   -2.03
2026-10-18   -1.29
2026-10-25    0.91
2026-11-01   -0.18
2026-11-08   -1.25
2026-11-15    1.24
Name: delhi, dtype: float64

In [37]:
ndf[(ndf["delhi"] > 0) & (ndf['mumbai'] > 0)]

            delhi  mumbai  bengluru  chennai
2026-07-12   0.47    0.09      0.38     0.44
2026-09-06   0.20    0.95     -0.08    -0.05

In [39]:
ndf.loc[ndf["delhi"] > 0, ["delhi", "mumbai"]]

            delhi  mumbai
2026-07-05   0.73   -1.18
2026-07-12   0.47    0.09
2026-07-26   0.11   -1.26
2026-08-02   0.46   -0.48
2026-09-06   0.20    0.95
2026-10-25   0.91   -1.03
2026-11-15   1.24   -0.36

In [ ]:
# ndf.loc[ndf["delhi"] > 0, ]