In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import make_regression, load_iris

# Using load_based dataset

In [4]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
dt = load_iris()

In [7]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [10]:
df = pd.DataFrame(dt.data, columns=dt.feature_names)

In [14]:
df.rename(columns={'sepal length (cm)':'sepal_length', 'sepal width (cm)':'sepal_width', 'petal length (cm)':'petal_length', 'petal width (cm)':'petal_width'}, inplace=True)

In [15]:
df

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [17]:
df['target'] = dt.target

In [18]:
df

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

# Using Make_based dataset

In [ ]:
x,y = make_regression(n_samples=20, n_features=4, bias=10.3, noise=1.8)

In [ ]:
x.shape

(20, 4)

In [ ]:
y.shape

(20,)

In [ ]:
df = pd.DataFrame(x).round(2)

In [ ]:
df

       0     1     2     3
0   0.10  1.25  0.38 -0.10
1   0.34  0.16  0.76 -2.14
2  -0.24 -0.53 -0.65 -0.00
3  -0.52  0.60  1.31 -2.33
4  -0.30  1.70  1.08 -0.35
5   1.42  0.95 -0.14  0.82
6   1.12  2.10 -0.99 -1.57
7  -0.18  0.03  1.33 -3.08
8  -0.08 -0.70  0.10 -1.06
9   1.37 -1.18  1.15 -1.07
10 -0.34 -0.15  0.29 -0.12
11 -0.38 -0.27  0.22 -1.07
12 -1.12  2.02 -0.37  1.05
13  1.34  1.50 -0.65 -2.90
14  0.67  0.94  0.16  0.54
15 -0.84  0.21 -0.26 -0.18
16 -0.52 -0.55 -0.36  2.40
17  0.46 -1.73  0.91 -0.66
18 -2.11  1.93 -2.70  1.01
19  0.52  0.06 -0.62 -0.25

In [ ]:
df.columns = ["col1", "col2", "col3", "col4"]

In [ ]:
df.rename()

In [ ]:
df

    col1  col2  col3  col4
0   0.10  1.25  0.38 -0.10
1   0.34  0.16  0.76 -2.14
2  -0.24 -0.53 -0.65 -0.00
3  -0.52  0.60  1.31 -2.33
4  -0.30  1.70  1.08 -0.35
5   1.42  0.95 -0.14  0.82
6   1.12  2.10 -0.99 -1.57
7  -0.18  0.03  1.33 -3.08
8  -0.08 -0.70  0.10 -1.06
9   1.37 -1.18  1.15 -1.07
10 -0.34 -0.15  0.29 -0.12
11 -0.38 -0.27  0.22 -1.07
12 -1.12  2.02 -0.37  1.05
13  1.34  1.50 -0.65 -2.90
14  0.67  0.94  0.16  0.54
15 -0.84  0.21 -0.26 -0.18
16 -0.52 -0.55 -0.36  2.40
17  0.46 -1.73  0.91 -0.66
18 -2.11  1.93 -2.70  1.01
19  0.52  0.06 -0.62 -0.25

In [ ]:
df.rename(columns={
    "col1":"delhi",
    "col2":"mumbai",
    "col3":"bengluru",
    "col4":"chennai"
}, inplace=True)

In [ ]:
df

    delhi  mumbai  bengluru  chennai
0    0.10    1.25      0.38    -0.10
1    0.34    0.16      0.76    -2.14
2   -0.24   -0.53     -0.65    -0.00
3   -0.52    0.60      1.31    -2.33
4   -0.30    1.70      1.08    -0.35
5    1.42    0.95     -0.14     0.82
6    1.12    2.10     -0.99    -1.57
7   -0.18    0.03      1.33    -3.08
8   -0.08   -0.70      0.10    -1.06
9    1.37   -1.18      1.15    -1.07
10  -0.34   -0.15      0.29    -0.12
11  -0.38   -0.27      0.22    -1.07
12  -1.12    2.02     -0.37     1.05
13   1.34    1.50     -0.65    -2.90
14   0.67    0.94      0.16     0.54
15  -0.84    0.21     -0.26    -0.18
16  -0.52   -0.55     -0.36     2.40
17   0.46   -1.73      0.91    -0.66
18  -2.11    1.93     -2.70     1.01
19   0.52    0.06     -0.62    -0.25

In [ ]:
pd.date_range("2026-07-05", periods=20, freq="W")

DatetimeIndex(['2026-07-05', '2026-07-12', '2026-07-19', '2026-07-26',
               '2026-08-02', '2026-08-09', '2026-08-16', '2026-08-23',
               '2026-08-30', '2026-09-06', '2026-09-13', '2026-09-20',
               '2026-09-27', '2026-10-04', '2026-10-11', '2026-10-18',
               '2026-10-25', '2026-11-01', '2026-11-08', '2026-11-15'],
              dtype='datetime64[ns]', freq='W-SUN')

In [ ]:
df.set_index(pd.date_range("2026-07-05", periods=20, freq="W"), inplace=True)

In [ ]:
df

            delhi  mumbai  bengluru  chennai
2026-07-05   0.10    1.25      0.38    -0.10
2026-07-12   0.34    0.16      0.76    -2.14
2026-07-19  -0.24   -0.53     -0.65    -0.00
2026-07-26  -0.52    0.60      1.31    -2.33
2026-08-02  -0.30    1.70      1.08    -0.35
2026-08-09   1.42    0.95     -0.14     0.82
2026-08-16   1.12    2.10     -0.99    -1.57
2026-08-23  -0.18    0.03      1.33    -3.08
2026-08-30  -0.08   -0.70      0.10    -1.06
2026-09-06   1.37   -1.18      1.15    -1.07
2026-09-13  -0.34   -0.15      0.29    -0.12
2026-09-20  -0.38   -0.27      0.22    -1.07
2026-09-27  -1.12    2.02     -0.37     1.05
2026-10-04   1.34    1.50     -0.65    -2.90
2026-10-11   0.67    0.94      0.16     0.54
2026-10-18  -0.84    0.21     -0.26    -0.18
2026-10-25  -0.52   -0.55     -0.36     2.40
2026-11-01   0.46   -1.73      0.91    -0.66
2026-11-08  -2.11    1.93     -2.70     1.01
2026-11-15   0.52    0.06     -0.62    -0.25

In [ ]:
df.to_excel("regression.xlsx")

In [ ]:
ndf = pd.read_excel("regression2.xlsx", index_col="Unnamed: 0")

In [ ]:
ndf

            delhi  mumbai  bengluru  chennai
2026-07-05   0.10    1.25      0.38    -0.10
2026-07-12   0.34    0.16      0.76    -2.14
2026-07-19  -0.24   -0.53     -0.65     0.00
2026-07-26  -0.52    0.60      1.31    -2.33
2026-08-02  -0.30    1.70      1.08    -0.35
2026-08-09   1.42    0.95     -0.14     0.82
2026-08-16   1.12    2.10     -0.99    -1.57
2026-08-23  -0.18    0.03      1.33    -3.08
2026-08-30  -0.08   -0.70      0.10    -1.06
2026-09-06   1.37   -1.18      1.15    -1.07
2026-09-13  -0.34   -0.15      0.29    -0.12
2026-09-20  -0.38   -0.27      0.22    -1.07
2026-09-27  -1.12    2.02     -0.37     1.05
2026-10-04   1.34    1.50     -0.65    -2.90
2026-10-11   0.67    0.94      0.16     0.54
2026-10-18  -0.84    0.21     -0.26    -0.18
2026-10-25  -0.52   -0.55     -0.36     2.40
2026-11-01   0.46   -1.73      0.91    -0.66
2026-11-08  -2.11    1.93     -2.70     1.01
2026-11-15   0.52    0.06     -0.62    -0.25

In [ ]:
ndf.loc[:,'delhi']

2026-07-05    0.10
2026-07-12    0.34
2026-07-19   -0.24
2026-07-26   -0.52
2026-08-02   -0.30
2026-08-09    1.42
2026-08-16    1.12
2026-08-23   -0.18
2026-08-30   -0.08
2026-09-06    1.37
2026-09-13   -0.34
2026-09-20   -0.38
2026-09-27   -1.12
2026-10-04    1.34
2026-10-11    0.67
2026-10-18   -0.84
2026-10-25   -0.52
2026-11-01    0.46
2026-11-08   -2.11
2026-11-15    0.52
Name: delhi, dtype: float64

In [ ]:
ndf[(ndf["delhi"] > 0) & (ndf['mumbai'] > 0)]

            delhi  mumbai  bengluru  chennai
2026-07-05   0.10    1.25      0.38    -0.10
2026-07-12   0.34    0.16      0.76    -2.14
2026-08-09   1.42    0.95     -0.14     0.82
2026-08-16   1.12    2.10     -0.99    -1.57
2026-10-04   1.34    1.50     -0.65    -2.90
2026-10-11   0.67    0.94      0.16     0.54
2026-11-15   0.52    0.06     -0.62    -0.25